//Function that is used to generate the HTML that will use the information entered into the prompt by the user when asked to add a manager
const managerGenerate = function (manager) {//Materialize is being used to create an icon that will be displayed after the name of the manager is displayed
    return `
    <div class ="col-4 mt-4">
        <div class="card">
            <div class="header-card bg-primary text-white rounded">
                <h4>${manager.name}</h2>
                <h5>Manager</h3><i class="material-icons">coffee</i>
            </div>

            <div class="body-card rounded">
                <p class="employee-ID">ID: ${manager.id}</p>
                <p class="employee-email">Email: <a href="mailto:${manager.email}">${manager.email}</a></p>
                <p class="manager-office">Office Number: ${manager.officeNumber}</p>
            </div>

        </div>
    </div>
    `;
}

//Function that is used to generate the HTML that will use the information entered into the prompt by the user when asked to add a new employee and an intern is selected
const internGenerate = function (intern) {//Materialize is being used to create an icon that will be displayed after the name of the intern is displayed
    return `
    <div class="col-4 mt-4">
        <div class="card">
            <div class="header-card bg-primary text-white rounded">
                <h4>${intern.name}</h2>
                <h5>Manager</h3><i class="material-icons">work</i>
            </div>

            <div class="body-card rounded">
                <p class="employee-ID">ID: ${intern.id}</p>
                <p class="employee-email">Email: <a href="mailto:${intern.email}">${intern.email}</a></p>
                <p class="intern-school">Office Number: ${intern.school}</p>
            </div>

        </div>
    </div>
    `;
}

//Function that is used to generate the HTML that will use the information entered into the prompt by the user when asked to add a new employee and an engineer is selcted
const engineerGenerate = function (engineer) {//Materialize is being used to create an icon that will be displayed after the name of the engineer is displayed
    return `
    <div class="col-4 mt-4">
        <div class="card">
            <div class="header-card bg-primary text-white rounded">
                <h4>${engineer.name}</h2>
                <h5>Engineer</h3><i class="material-icons">laptop</i>
            </div>

            <div class="body-card rounded">
                <p class="employee-ID">ID: ${engineer.id}</p>
                <p class="employee-email">Email: <a href="mailto:${engineer.email}">${engineer.email}</a></p>
                <p class="engineer-github">GitHub Username: <a href="https://github.com/${engineer.github}">${engineer.github}</a></p>
            </div>

        </div>
    <div>    
    `;
}

//This function is being used to create an array that will be used to generate the webpage. This function will ultimately generate the cards for each employee to be added to the web page
GenerateHTML = (pageData) => {

    teamPage = [];
    //This for loop is cycling through each employee that was added and is setting the const employee to equal each employee in the array's index
    for (let i = 0; i < pageData.length; i++) {
        const employee = pageData[i];
        const employeeRole = employee.getRole(); //The const employeeRole is being set to equal employee.getRole in order to get the role of each employee. The role of the employee will be important in determinng which card to use for which employee
        //The following if statement is checking the employee role and creating the card that matches that employee's role. 
        if (employeeRole === "Manager") {
            const cardManager = managerGenerate(employee);

            teamPage.push(cardManager); //This is pushing the cardManger to the teamPage array
        } else if (employeeRole === "Intern") {
            const cardIntern = internGenerate(employee);

            teamPage.push(cardIntern); //This is pushing the cardInternto the teamPage array
        } else if (employeeRole === "Engineer") {
            const cardEngineer = engineerGenerate(employee);

            teamPage.push(cardEngineer);//This is pushing the cardEngineer to the teamPage array
        }
        
    }
    //The const cardsEmployee is being set to equal teamPage.join, which will join the strings in the array and allow us to display each employee card to the web page
    const cardsEmployee = teamPage.join('');

    const teamGenerate = teamGeneratePage(cardsEmployee); //The const temGenerate has been set to the function teamGeneratePage, which will be the function that is used to generate the html page. cardsEmployee is being passed through the function, as the various employee cards will be generated by this.
    return teamGenerate;
}
//Function that will generate the html page
const teamGeneratePage = function (cardsEmployee) {
    return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Project Team Profile</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous"> <!-- Allows us to use bootstrap for our styling-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="./style.css">
    </head>
    <body>
        <header class="container-fluid bg-primary">
            <h1 class="container-fluid text-center text-white">Project Team Profile</h1>
        </header>

        <main>
            <div class="container-fluid" id="card-container">
                <div class="row justify-content-center">
                    ${cardsEmployee}
                </div>
            </div>
        </main>
    </body>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>   
    </html>
    
`;
}

//export GenerateHTML so that it can be used on index.js 
module.exports = GenerateHTML;